### ISSUE TITLE
encoding option from papaparse is not working

### ISSUE THREAD

**Issue by inuue** [beamworks/react-csv-importer#55]
Hey! I very much like this csv importer. Tried working with foreign languages and encoding config is not working for me.
`<Importer
          // other configs
          encoding={'windows-1250'}
        >`

Error I am getting using other encoding than 'utf-8':
`Import error: Unknown encoding: windows-1250`

When I stay with utf-8 data is encoded like this:
`test��,teast��,����as@fdsa.ok,`

Would be nice to have all options from papaparse. I tested react version and it works with encoding:
https://react-papaparse.js.org/docs#config 

`config={{
   encoding: 'windows-1250',
}}`

**Comment by unframework** [comment]
Thanks for reporting this, looks like the `encoding` option needs some special treatment. Adding this to my to-do list.

**Comment by unframework** [comment]
I did a bit of a deep dive into encoding/streaming issues today but did not finish yet. To explain the error above - the way that the CSV streaming support works right now, it uses Node buffers instead of browser FileReader. This is to avoid some multibyte chunk boundary issues with PapaParse: https://github.com/mholt/PapaParse/issues/908. Hence only UTF and legacy latin1 encodings are supported.

My plan now is to switch to using browser TextDecoder instead of Node buffers to allow legacy encodings, just need to do a bit more work on the stream shim.

Thanks for the wait!

**Comment by unframework** [comment]
This should be now working in v0.6.0 - all the FileReader API encodings are now supported, including `windows-1250`. Please reopen issue if this persists, cheers!
