### ISSUE TITLE
Google Sheets is skipping first row

### ISSUE THREAD

**Issue by jessehanley** [beamworks/react-csv-importer#61]
Hey @unframework, 

Got a weird one today that our support team ran into: when you export to CSV from Google Sheets and import into `react-csv-importer` it often skips the first row.

To replicate we head on over to Google Sheets and create a simple spreadsheet with just one row and header:

![image](https://user-images.githubusercontent.com/6285267/152712637-1b49c56e-da28-4371-a10d-6f7d7067584b.png)

When we export it as a `.csv` file and import it into our importer it's just blank:

![image](https://user-images.githubusercontent.com/6285267/152712725-4bfd053d-d514-4658-adce-8d57133f4eab.png)

If we go ahead and increase it to two lines we run into a similar problem: 

![image](https://user-images.githubusercontent.com/6285267/152712870-d6da456c-366a-4e8a-80aa-b05f61cea948.png)

It skips the first row again:

![image](https://user-images.githubusercontent.com/6285267/152712900-3d8c04bd-4193-416c-9406-f5606350c09c.png)

Can't figure this one out. Have upgraded to the latest version of the plugin too. Issue happens on the demo page as well so not just our repository.

Not a big issue and no rush — was just curious if you've come across it?

Appreciate you!

**Comment by unframework** [comment]
Hmm, I looked into this and was able to repro - it seems the final import works ok, but in preview the last line does not show up.

This is because my preview logic assumed that PapaParse just emits entire initial file content as one stream chunk, but it so happens that the last line always gets "flushed out" separately. So, luckily no data loss but it looks broken for small files, of course.

Will get a fix out in next point release (there are a few other streaming/parsing cleanups to release as well).

**Comment by unframework** [comment]
This should be fixed in v0.6.0, please reopen if this persists. And thanks again for the repro case + screenshots!
