### ISSUE TITLE
How to do validation when user drag and drop column

### ISSUE THREAD

**Issue by Wooody82** [beamworks/react-csv-importer#89]
Hi
Is there anyway to do a validation after user drag-drop data to column and display error message if data not valid and they cant continue to import.

I see validation only for required fields but how could we do more custom validation!
Thanks

**Comment by unframework** [comment]
This is a useful feature, but currently the importer only reads the first few rows before drag-drop is shown to the user. This limit is intentional because e.g. the file could be huge, so reading all the content at once would be very slow.

We could try to validate just based on those first few rows of course, and I will think about how to expose that ability, but it will not be very reliable since you are only checking <1% of the data in many cases.

I will close for now and add to my feature planning list; please feel free to reopen and add more comments of course. Thanks!
